// Concepts + expert insight for each problem.
// { tags: [...techniques to know...], tip: "what makes the expert solution better" }
const CONCEPTS = {
  1:  { tags: ["Array.reduce", "accumulator pattern"], tip: "Use arr.reduce((a,b)=>a+b, 0). Always pass the initial value 0 so an empty array returns 0, not undefined." },
  2:  { tags: ["Math.max", "spread operator", "reduce"], tip: "Math.max(...arr) is elegant but overflows the call stack on huge arrays; reduce is O(n) and safe at any size." },
  3:  { tags: ["Math.min", "spread operator", "reduce"], tip: "Same spread-vs-reduce tradeoff as max — reduce scales to millions of elements." },
  4:  { tags: ["reduce", "empty-array guard"], tip: "Sum then divide by length — but guard length===0 to avoid dividing by zero (NaN)." },
  5:  { tags: ["two-pointer swap", "in-place vs new array"], tip: "Swap from both ends toward the middle: O(n) time, O(1) space — the expert in-place technique." },
  6:  { tags: ["modulo %", "filter().length", "reduce counting"], tip: "n % 2 === 0 for even. reduce counts in one pass without building a throwaway array." },
  7:  { tags: ["Array.filter", "pure predicate"], tip: "filter returns a NEW array; keep the callback side-effect free." },
  8:  { tags: ["Array.map", "immutability"], tip: "map for 1:1 transforms — never mutate the original array." },
  9:  { tags: ["Set", "spread from Set"], tip: "[...new Set(arr)] dedupes in O(n). A nested-loop check is O(n²)." },
  10: { tags: ["single-pass tracking", "avoid full sort"], tip: "Track largest + secondLargest in ONE pass (O(n)) instead of sorting (O(n log n)). Watch for duplicates of the max." },
  11: { tags: ["Array.includes", "Set for repeated lookups"], tip: "includes is O(n). If you query many times, build a Set once for O(1) lookups." },
  12: { tags: ["spread operator", "concat"], tip: "[...a, ...b] or a.concat(b) — both return a new array without mutating." },
  13: { tags: ["Array.findIndex", "short-circuit"], tip: "findIndex stops at the first match — don't scan the whole array with a manual loop." },
  14: { tags: ["reduce counter", "filter().length"], tip: "reduce counts matches in one pass without an intermediate array." },
  15: { tags: ["Array.map"], tip: "Pure 1:1 transform — x => x*x." },
  16: { tags: ["single reduce", "filter+reduce"], tip: "Do the filter-and-sum in ONE reduce to avoid two passes over the array." },
  17: { tags: ["Array.flat", "reduce + concat"], tip: "arr.flat() handles one level by default; flat(depth) or flat(Infinity) for deeper." },
  18: { tags: ["pop + unshift", "modular indexing"], tip: "arr.unshift(arr.pop()) rotates by 1. For rotate-by-k use modular arithmetic instead of shifting k times." },
  19: { tags: ["Set membership", "filter"], tip: "Put one array in a Set, filter the other → O(n+m). Nested loops are O(n·m)." },
  20: { tags: ["two-pointer", "stable partition", "in-place"], tip: "A write-index pointer moves non-zeros forward keeping order: O(n) time, O(1) space." },
  21: { tags: ["reduce", "identity value 1"], tip: "Initial value must be 1 (not 0). Watch: a single 0 in the array makes the whole product 0." },
  22: { tags: ["slice in a loop", "index stepping"], tip: "Step the index by chunk size and slice — slice doesn't mutate the source." },
  23: { tags: ["running accumulator", "prefix sum"], tip: "This IS the prefix-sum pattern — the foundation for fast range-sum queries in real DSA." },
  24: { tags: ["Set", "filter"], tip: "Build a Set of B, then filter A → O(n+m) instead of O(n·m)." },
  25: { tags: ["reduce to object", "bucketing"], tip: "reduce into { even:[], odd:[] } — the generic bucketing/partition pattern." },

  26: { tags: ["split-reverse-join", "two-pointer", "spread"], tip: "[...s].reverse().join('') handles multi-byte unicode better than s.split('')." },
  27: { tags: ["two-pointer", "normalize input"], tip: "Compare from both ends inward: O(n) time, O(1) space — no need to build a reversed copy." },
  28: { tags: ["Set of vowels", "regex match"], tip: "A vowel Set gives O(1) membership; s.match(/[aeiou]/gi)?.length is the concise version." },
  29: { tags: ["split/map/join", "charAt + toUpperCase"], tip: "Split on spaces and capitalize each; regex replace(/\\b\\w/g, c=>c.toUpperCase()) is the expert one-liner." },
  30: { tags: ["frequency map", "object/Map counter"], tip: "The frequency-map pattern — the backbone of anagram, most-frequent, and first-unique problems." },
  31: { tags: ["two-pass frequency map", "Map preserves order"], tip: "Count first, then find the first char with count 1. A Map keeps insertion order reliably." },
  32: { tags: ["frequency-map compare", "sort compare"], tip: "Compare char counts in O(n) instead of sorting both strings (O(n log n))." },
  33: { tags: ["regex replace", "\\s class"], tip: "s.replace(/\\s/g,'') strips ALL whitespace (tabs, newlines), not just literal spaces." },
  34: { tags: ["trim + split(/\\s+/)"], tip: "Trim then split on /\\s+/ so double spaces don't produce empty-string 'words'." },
  35: { tags: ["reduce max-by", "split"], tip: "reduce tracking the longest word — one pass, no sorting needed." },
  36: { tags: ["regex /g flag", "replaceAll"], tip: "replace(/ /g,'-') or replaceAll — a plain replace(' ','-') only changes the FIRST space." },
  37: { tags: ["anchored regex /^\\d+$/", "input validation"], tip: "Anchor with ^ and $. Beware Number()/parseInt accept signs, decimals, and whitespace." },
  38: { tags: ["frequency map + max scan"], tip: "Build the count map, then a single scan for the max entry." },
  39: { tags: ["slice", "length guard"], tip: "Only append '...' when the string actually exceeds the limit." },
  40: { tags: ["char-code ranges", "regex match length"], tip: "(s.match(/[A-Z]/g)||[]).length, or compare c===c.toUpperCase()." },
  41: { tags: ["split/reverse/join"], tip: "Split on spaces, reverse the array, join — trim first to avoid empty tokens." },
  42: { tags: ["concatenation trick", "includes"], tip: "s2 is a rotation of s1 iff lengths match AND (s1+s1).includes(s2). The classic trick." },
  43: { tags: ["stopword Set", "index-aware map"], tip: "Always capitalize the FIRST word; skip small words (a, the, of) via a Set for the rest." },
  44: { tags: ["frequency map filter>1", "Set of seen"], tip: "Count chars, then return those with count > 1 (unique duplicates only)." },
  45: { tags: ["group consecutive runs", "run counter"], tip: "Walk once counting consecutive equal chars — the core of run-length compression." },

  46: { tags: ["object as counter", "|| 0 init"], tip: "obj[k] = (obj[k] || 0) + 1 — the idiomatic frequency counter." },
  47: { tags: ["spread", "Object.assign", "shallow vs deep"], tip: "{...a, ...b} is a SHALLOW merge — nested objects stay shared by reference." },
  48: { tags: ["Object.keys"], tip: "Returns own enumerable keys as an array." },
  49: { tags: ["Object.values"], tip: "Pairs with Object.entries when you need key AND value." },
  50: { tags: ["Object.entries", "reduce/loop"], tip: "Swap key<->value; duplicate values collide (last one wins)." },
  51: { tags: ["Object.entries + reduce max-by"], tip: "reduce over entries comparing values — one pass, no sort." },
  52: { tags: ["Object.keys().length", "no == {}"], tip: "Object.keys(o).length === 0. You can NOT compare objects with == / ===." },
  53: { tags: ["Object.values + reduce"], tip: "Object.values(o).reduce((a,b)=>a+b, 0)." },
  54: { tags: ["destructuring rest", "avoid delete"], tip: "const { [key]:_, ...rest } = obj returns a NEW object without mutating the original." },
  55: { tags: ["reduce to buckets", "groupBy pattern"], tip: "The generic groupBy — one of the most reused data-shaping patterns in real code." },
  56: { tags: ["Set", "spread"], tip: "Set is the O(n) dedupe tool; [...new Set(arr)] to get an array back." },
  57: { tags: ["Set membership + filter"], tip: "Set one side, filter the other → O(n+m)." },
  58: { tags: ["Set.size"], tip: "new Set(arr).size counts uniques in one step." },
  59: { tags: ["Object.fromEntries"], tip: "Object.fromEntries(pairs) — the exact inverse of Object.entries." },
  60: { tags: ["entries compare", "key union"], tip: "Compare values on shared keys; decide explicitly how to treat keys missing on one side." },

  61: { tags: ["modulo %", "bitwise & 1"], tip: "n % 2 is clearest; n & 1 is the bit-trick for odd." },
  62: { tags: ["trial division to √n", "early exit"], tip: "Only test divisors up to √n and skip evens — a huge speedup over checking up to n." },
  63: { tags: ["loop product", "recursion", "BigInt"], tip: "Overflows past 20! in normal numbers — use BigInt for large n." },
  64: { tags: ["iterative two-variable", "avoid naive recursion"], tip: "Iterative Fibonacci is O(n). Naive recursion is O(2ⁿ) — never do it unmemoized." },
  65: { tags: ["modulo/divide digit loop"], tip: "n%10 gets the last digit, Math.floor(n/10) drops it — the digit-extraction loop." },
  66: { tags: ["digit loop building a number", "sign handling"], tip: "Build result as r = r*10 + n%10. Mind negative numbers and trailing zeros." },
  67: { tags: ["reverse-and-compare", "math vs string"], tip: "Reverse the number mathematically (no string) for the expert version." },
  68: { tags: ["Euclidean algorithm"], tip: "gcd(a,b) = gcd(b, a%b), O(log n). LCM = a*b / gcd(a,b)." },
  69: { tags: ["formula", "pure functions"], tip: "F = C*9/5 + 32. Keep each direction as a separate pure function." },
  70: { tags: ["Sieve of Eratosthenes"], tip: "The Sieve is O(n log log n) — far faster than testing each number for primality." },
  71: { tags: ["Math.sqrt + integer check"], tip: "Number.isInteger(Math.sqrt(n)); beware float rounding error for very large n." },
  72: { tags: ["String(n).length", "Math.log10"], tip: "String(n).length is simplest; Math.floor(Math.log10(n))+1 is the math version." },
  73: { tags: ["digit loop max", "Math.max on split"], tip: "One pass with %10 tracking the max digit." },
  74: { tags: ["digit extraction + power sum"], tip: "Sum each digit^(number of digits) and compare — the narcissistic/Armstrong check." },
  75: { tags: ["Math.round + scaling", "toFixed"], tip: "Math.round(n * 10**d) / 10**d. toFixed returns a STRING and has rounding edge cases." },

  76: { tags: ["for loop basics"], tip: "The canonical counted loop from 1 to N." },
  77: { tags: ["single loop", "template literals"], tip: "Format cleanly with `${n} x ${i} = ${n*i}` template strings." },
  78: { tags: ["modulo combos", "condition order"], tip: "Check %15 (or both %3 and %5) FIRST — order of conditions is the classic FizzBuzz trap." },
  79: { tags: ["nested loops", "String.repeat"], tip: "'*'.repeat(i) beats writing an inner loop." },
  80: { tags: ["continue statement", "modulo"], tip: "if (i % 7 === 0) continue; — the guard/skip pattern." },
  81: { tags: ["loop step 2", "closed-form"], tip: "Step by 2, or use the closed form for sum of evens for O(1)." },
  82: { tags: ["decrementing loop"], tip: "A reverse-direction for loop." },
  83: { tags: ["loop vs Gauss formula"], tip: "n*(n+1)/2 is O(1) — Gauss's trick vs an O(n) loop." },
  84: { tags: ["reuse isPrime helper", "sieve"], tip: "Reuse one isPrime helper; a sieve is faster if you need the whole range." },
  85: { tags: ["nested loops", "spaces + stars math"], tip: "Per row: leading spaces = n-i, stars = 2i-1." },

  86: { tags: ["function definition", "arrow function"], tip: "A pure function: const square = n => n*n." },
  87: { tags: ["higher-order function", "callback"], tip: "Functions are first-class values — pass one in and invoke it in a loop." },
  88: { tags: ["higher-order fn", "callback signature (el,i,arr)", "immutability"], tip: "Match the real signature callback(element, index, array) and return a NEW array." },
  89: { tags: ["predicate callback", "push on truthy"], tip: "Keep elements where the predicate returns truthy." },
  90: { tags: ["accumulator", "initial-value handling"], tip: "The tricky part: when NO initial value is passed, use the first element and start at index 1." },
  91: { tags: ["recursion", "base + recursive case", "head/tail split"], tip: "Base: empty→0. Recurse on the tail. Watch stack depth on very large arrays." },
  92: { tags: ["recursion", "string slicing"], tip: "reverse(s.slice(1)) + s[0] — the classic string recursion." },
  93: { tags: ["recursion", "base case n<=1"], tip: "The base case prevents infinite recursion; iterative avoids stack-overflow for big n." },
  94: { tags: ["recursion", "Array.isArray", "reduce + concat"], tip: "Recurse when an element is itself an array. Built-in shortcut: arr.flat(Infinity)." },
  95: { tags: ["closures", "function returning function", "argument accumulation"], tip: "Closures capture args across calls. A variadic curry handles arbitrary arity, not just 3." },
  96: { tags: ["closures", "setTimeout / clearTimeout", "timer id in closure"], tip: "clearTimeout the previous timer on every call so only the LAST call fires. The heart of rate-limiting." },
  97: { tags: ["closures", "cache Map", "key serialization"], tip: "Cache results keyed by args (e.g. JSON.stringify) — trades memory for speed. This is the seed idea behind DP." },
  98: { tags: ["recursion", "isArray branch", "accumulate count"], tip: "Recurse into sub-arrays and sum the matches." },
  99: { tags: ["Promises", "resolve-when-all-done counter", "preserve order"], tip: "Track a completion counter, store each result by its index to keep order, and reject on the first error." },
  100:{ tags: ["async/await", "await-in-loop vs Promise.all", "concurrency"], tip: "Sequential = await one at a time; parallel = await Promise.all([...]). Knowing WHEN to use each is the key perf skill." },
};
